### ISSUE TITLE
单击图片关闭页面，页面将要关闭瞬间再次点击查看大图，app崩溃

### ISSUE THREAD

**Issue by BaiYuMoO** [Awent/PhotoPick-Master#12]
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@424b90d is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:853)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
        at android.app.Dialog.show(Dialog.java:329)
        at android.support.v7.app.AlertDialog$Builder.show(AlertDialog.java:1006)
        at com.awen.photo.photopick.ui.PhotoPagerActivity.saveImageDialog(PhotoPagerActivity.java:527)
        at com.awen.photo.photopick.ui.PhotoPagerActivity.onLongClick(PhotoPagerActivity.java:260)
        at android.view.View.performLongClickInternal(View.java:6694)
        at android.view.View.performLongClick(View.java:6652)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$1.handleMessage(SubsamplingScaleImageView.java:297)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by Awent** [comment]
@BaiYuMoO 我刚刚更新了下，你试试v2.06版本。你也可以pull request的，我会尽快合并的

**Comment by BaiYuMoO** [comment]
@Awent 刚测试了，问题没有再复现了
